### ISSUE TITLE
Adding Mentions view triggers keyboardHide and then keyboardShow

### ISSUE THREAD

**Issue by simonsmiley64** [linkedin/Hakawai#52] opened 2017-09-11 02:16 UTC
I have added the mentions plugin to my app and have noticed that when the keyboard is showing, loading the mention view will cause the keyboard to re-call the observer notifications.

Load view:
    keyboardWillShow
    keyboardDidShow

These occur as expected when we load the keyboard.

Type the mention character (# or @)
    keyboardWillHide
    keyboardDidHide
    keyboardWillShow
    keyboardDidShow

The keyboard doesn't change at all but these functions are still called.

This is causing issues for me as I am refreshing the tableView under the mentions view when the keyboard appears. Each time I open or close the mentions view this is happening. 

Do you have any idea why this could be happening with the mentions view and plugin?

Simon

**Comment by simonsmiley64** [comment] 2017-09-11 23:21
It looks like the problem is coming from this function:

```
- (void)cycleFirstResponderStatusWithMode:(HKWCycleFirstResponderMode)mode cancelAnimation:(BOOL)cancelAnimation {
    BOOL usingAbstraction = self.abstractionLayerEnabled;
    if (usingAbstraction) {
        [self.abstractionLayer pushIgnore];
    }
    self.firstResponderIsCycling = YES;
    [self resignFirstResponder];
```

We are resigning the first responder each time this function is being called. 

Is there any reason why we need to resign the first responder here each time?

**Comment by om-ha** [comment] 2017-10-08 13:40
I wish this would be fixed.

**Comment by narlei** [comment] 2017-10-11 16:28
This happens because Hakawai need remove keyboard Proactive Suggestions. Because this a bug occurs when use 3D Touch selector to select a mention.

Issue here:
https://github.com/linkedin/Hakawai/issues/33

Fix PR here:
https://github.com/linkedin/Hakawai/pull/42

**Comment by sergstav** [comment] 2018-11-29 17:00
@dgattey Any fix on this?

**Comment by dgattey** [comment] 2019-03-01 08:12
Waiting for tests on #42 to close out #33 and this too. Closing this as a duplicate of #33 for now

**Closed by dgattey** 2019-03-01 08:12 UTC
