### ISSUE TITLE
3D touch mention selection crash

### ISSUE THREAD

**Issue by radko93** [linkedin/Hakawai#56] opened 2017-11-29 16:52 UTC
How to reproduce:
1. Select a mention using 3D touch
2. Drag it over another mention
3. App will crash

Maybe you will have any idea @narlei?

**Comment by narlei** [comment] 2017-11-29 19:23
@radko93 yes, the problem is when toggle Keyboard suggestions, need resign and become first responder. I Solved this in PR https://github.com/linkedin/Hakawai/pull/42
Only not making the toggle in that moment. Today I have 2k+ users with this code and working withouts problems.

**Comment by radko93** [comment] 2017-11-30 13:32
It's a different issue, this one started to be a problem in iOS 11 since the drag and drop was introduced. This demo includes your PR (same behaviour on Hakawai demo app)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7029942/33433259-2e308d6a-d5db-11e7-9fa5-6415323209f3.gif)

**Comment by dgattey** [comment] 2019-03-01 08:18
Closing as duplicate of #33, thanks

**Closed by dgattey** 2019-03-01 08:18 UTC
Labels: bug
