### ISSUE TITLE
Insert Control Character programmatically and start mention picker automatically

### ISSUE THREAD

**Issue by PatrickAdams** [linkedin/Hakawai#43] opened 2017-06-10 04:50 UTC
I want to do exactly what the LinkedIn iPhone app is doing. Tap an @ button in the inputAccessoryView which them inserts the @ symbol into the UITextView and starts the mention picker dropdown. 

I have the beginning part working. When I tap the button it inserts my control character (@) but it does not start the mention picker. This only happens when I actually type an @ symbol.

Any help with this would be great appreciated. I have a feeling it's a simple fix and I am just missing something.

I thought the method `textViewDidProgrammaticallyUpdate` was the key but it doesn't seem to be working for me.

**Comment by dgattey** [comment] 2019-03-01 09:03
Duplicate of #18

**Closed** 2019-03-04 17:53 UTC
Labels: duplicate
